name = "poker"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-07"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
durable_objects_persist = true

[durable_objects]
bindings = [
    {name = "GAME", class_name = "Game"},
]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[[migrations]]
tag = "v2"
new_classes = ["Game"]
deleted_classes = ["Counter"]