name = "poker"
type = "javascript"
usage_model = ''
compatibility_flags = []
compatibility_date = "2021-10-07"
workers_dev = false
route = "*planningpoker.games/api*"
zone_id = "b381a74a99cea88a48fd3999c9d04e90"

# USER is the "planning-poker-user" namespace
kv_namespaces = [
    { binding = "USER", id = "b1f78e3dc5ac475cb1f867b6db37bcb0" },
    { binding = "SESSION", id = "7e637ccc57574d3091200692d0e92258" },
    { binding = "GAME", id = "c39cdc3092bb4e21b607b87fc790597e" }
]

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
durable_objects_persist = false
env_path = ".env.local"

[durable_objects]
bindings = [
    {name = "GAME_DO", class_name = "GameDO"},
]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[[migrations]]
tag = "v2"
new_classes = ["Game"]
deleted_classes = ["Counter"]

[[migrations]]
tag = "v3"
new_classes = ["GameDO"]
